export const KLO_ACRONYMS = [
  'Kalkulator Lokalnego Opodatkowania',
  'Kompletne Liczenie Obowiązków',
  'Kreator Lekkich Obliczeń',
  'Kieszonkowy Likwidator Obciążeń',
  'Kalkulator Likwidujący Obowiązki',
  'Krajowy Licznik Obciążeń',
  'Księgowy Likwidator Obliczeń',
  'Kompilator Liczb Ostatecznych',
  'Kasownik Leśnych Obaw',
  'Kalkulator Lekkich Obciążeń',
  'Kalkulator Lokalnych Obowiązków',
  'Kalkulator Legalnych Obliczeń',
  'Kompanion Liczenia Obrotów',
  'Korektor Liczb i Obciążeń',
  'Korektor Lokalnego Opodatkowania',
  'Księgowy Liczący Obowiązki',
  'Koniec Liczenia Obciążeń',
  'Koniec Lęku o Obliczenia',
  'Koniec Labiryntu Obowiązków',
  'Krajowy Lek na Obowiązki',
  'Kapitalny Licznik Obrotów',
  'Kapitał, Liczby, Obowiązki',
  'Kasa, Liczby, Ordynacja',
  'Katalog Liczb i Obciążeń',
  'Kulturalny Likwidator Obaw',
  'Kalkulator Legalnych Obowiązków',
  'Kompendium Liczb i Obciążeń',
  'Korektor Liczeń Obywatelskich',
  'Księgowy Liczący Operacje',
  'Koniec Liczenia, Odetchnij',
  'Kłopot Leci Overboard',
  'Kawa, Liczby, Ojej',
  'Klikasz, Liczy, Oddychasz',
  'Ktoś Liczy, Oby dobrze',
  'Kapitał, Lokaty, Obroty',
  'Kalkulator Linii Obrotu',
  'Księga Liczb i Obrotów',
  'Kapitałowy Licznik Operacji',
  'Krajowy Licencjonowany Obliczator',
  'Kancelaryjny Licznik Oświadczeń',
  'Katalog Legalizacji Obciążeń',
  'Koordynator Legislacyjnych Obowiązków',
];
